<div id="page" class="hfeed site pure-g-r">
<div class="pure-u sidebar" role="banner">
<header id="masthead" class="site-header">
<div class="site-branding">
    <h1 class="site-title"><a href="/" rel="home">goer.org</a></h1>
    <h2 class="site-description">Writing, code, etc.</h2>
</div>
<nav class="main-navigation" role="navigation">
<ul class="menu">
	<li><a href="/Journal/">Journal</a></li>
	<li><a href="/YUI/">YUI 3 Cookbook</a></li>
	<li><a href="/HTML/">HTML Tutorial</a></li>
	<li><a href="/About/">About</a></li>
</ul>
</nav>
</header>
</div>
<div id="content" class="site-content pure-u">
<div id="primary" class="content-area">
