<!DOCTYPE html>
<html>
<head>
    <title>Crazy Mike's Shack O' Law</title>
    <?php include $_SERVER['DOCUMENT_ROOT'].'/assets/inc/head_assets.inc'; ?>
</head>
<body>
    <div id="main">
        <?php include $_SERVER['DOCUMENT_ROOT'].'/assets/inc/header.inc'; ?>
        <div id="text">
	<h1>Crazy Mike's Shack-o-Law</h1>
<p>
	Need free legal advice?  Emphasis on free?
</p>
<p>
	Well, you've come to the right place.  Mike Holy, attorney extraordinaire, is 
	ready to untangle the vagaries of the law for you!  Just type your question into the text box
	and Mike will answer your question instantaneously.
	Yeah, he's that good. So hit that submit button.  Trained lawyers are 
	standing by!
</p>
<?php 
$question = isset($_POST['question']) ? $_POST['question'] : null;
$path = "/big/dom/xgoer/cgi-bin/dada/bin";
$dada_cmd = "$path/dada $path/legal.pb";
$submit = array(
  "You can't HANDLE the truth!",
  "Help me, Crazy Mike!",
  "I am The Law",
  "No, YOU'RE out of order!",
  "If the glove don't fit..."
);
?>

<h2>Post Your Question</h2>
<form name="legal" action="/Toys/Law/" method="post">
<p><input type="text" size="65" name="question" value="<?php echo $question; ?>"></p>
<p><input type="submit" value="<?php echo $submit[array_rand($submit)]; ?>"></p>
</form>

<?php if ($question != null) { ?>
	<h2><?echo filter_var($question, FILTER_SANITIZE_STRING); ?></h2>
	<p><?php echo system($dada_cmd); ?> </p>
<?php } ?>

<h3>Disclaimer</h3>
<p class="footnote">
	All answers to legal questions are completely random, generated by the famous 
	<a href="http://dev.null.org/dadaengine/" title="Huzzah for the Dada Engine!">Dada Engine</a>.
	Legal advice generated by the Dada Engine should not be used in a court of law.
</p>
<?php include $_SERVER['DOCUMENT_ROOT'].'/assets/inc/footer.inc'; ?>
        </div>
    </div>
</body>
</html>
